import Head from "next/head";
import styles from "../styles/Home.module.css";
import { sanityClient, urlFor } from "../lib/sanity";

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
  const recipe = recipes;

  return (
    <div className={styles.container}>
      <Head>
        <title>Shaun&apos;s Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return {
    props: {
      recipes,
    },
  };
}
